/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort.algorithms.comparions;

import org.apache.commons.io.IOUtils;
import sort.algorithms.comparions.implementations.BubbleSort;
import sort.algorithms.comparions.implementations.MergeSort;
import sort.algorithms.comparions.implementations.QuickSort;
import sort.algorithms.comparions.interfaces.ISortAlgorithm;
import sort.algorithms.comparions.utils.FileCreator;
import sort.algorithms.comparions.utils.FilesUtils;
import sort.algorithms.comparions.utils.InputCreator;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class App {
    private static BubbleSort bubbleSort = new BubbleSort();
    private static QuickSort quickSort = new QuickSort();
    private static MergeSort mergeSort = new MergeSort();


    public static void main(String[] args) throws IOException {
        try {
            final int size = 100000;
            final String folder = "/Users/estevaowatanabe/Desktop/projects/sort-algorithms-comparions";

            createInputFiles(folder, size);

            System.out.println("READING BUBBLE SORT FILES");
            readInputFilesByAlgorithm(folder + "/bubbleSort", bubbleSort);

            System.out.println("READING QUICK SORT FILES");
            readInputFilesByAlgorithm(folder + "/quickSort", quickSort);

            // System.out.println("READING MERGE SORT FILES");
            //readInputFilesByAlgorithm(folder + "/mergeSort", mergeSort);


//            System.out.println("Measuring Quick sort");
//            QuickSort quickSort = new QuickSort();
//            measureSortAlgorithm(quickSort, quickNumbers);

//            System.out.println("Measuring Merge Sort");
//            MergeSort mergeSort = new MergeSort();
//            measureSortAlgorithm(mergeSort, mergeNumbers);

            System.out.println("Measuring Bubble Sort");
            BubbleSort bubbleSort = new BubbleSort();
            measureSortAlgorithm(bubbleSort, numbers);
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }


    }

    private static void createInputFiles(String folder, int size) throws IOException {

        //bubble sort
        Map<String, int[]> inputs = new HashMap<>();

        //bubble sort
        int[] orderedAscArray = InputCreator.createOrderedAscInputs(size);
        int[] orderedDescArray = InputCreator.createOrderedDescInputs(size);
        int[] randomArray = InputCreator.createRandomInputs(size);

        inputs.put("bubbleSort/ordered_asc_array.txt", orderedAscArray);
        inputs.put("bubbleSort/ordered_desc_array.txt", orderedDescArray);
        inputs.put("bubbleSort/random_array.txt", randomArray);


        inputs.put("quickSort/ordered_asc_array.txt", orderedAscArray);
        inputs.put("quickSort/ordered_desc_array.txt", orderedDescArray);
        inputs.put("quickSort/random_array.txt", randomArray);


        inputs.put("mergeSort/ordered_asc_array.txt", orderedAscArray);
        inputs.put("mergeSort/ordered_desc_array.txt", orderedDescArray);
        inputs.put("mergeSort/random_array.txt", randomArray);

        inputs.forEach((fileName, input) -> {
            String content = formatInputs(input);
            String pathFile = folder + "/" + fileName;

            try {
                FileCreator.createFile(pathFile, content);
            } catch(IOException e) {
                System.out.println("ERROR CREATING THE FILE: " + pathFile);
            }
        });
    }

    private static String formatInputs(int[] input) {
        String[] inputStringified = Arrays.stream(input)
                .mapToObj(String::valueOf)
                .toArray(String[]::new);

        return String.join(",", inputStringified);
    }


    private static void measureSortAlgorithm(ISortAlgorithm algorithm, int[] numbers) {
        Instant startInstant = Instant.now();

        int[] sortedNumbers = algorithm.sort(numbers);
        Instant endInstant = Instant.now();

        Duration duration = Duration.between(startInstant, endInstant);
        long durationInNanos = duration.toNanos();
        long durationInMillis = duration.toMillis();
        long durationInSeconds = duration.toSeconds();

        System.out.println("TIME ELAPSED");
        System.out.println("NANOSECONDS: " + durationInNanos);
        System.out.println("MILLISECONDS: " + durationInMillis);


        System.out.println();
    }

    public static void readInputFilesByAlgorithm(String folder, ISortAlgorithm algorithm) throws FileNotFoundException, IOException {
        Set<File> files = FilesUtils.listFilesFromDirectory(folder);

        for(File file : files) {
            FileInputStream inputStream = new FileInputStream(file);
            String content = IOUtils.toString(inputStream, StandardCharsets.UTF_8);
            String[] contentSplit = content.split(",");
            int[] input = new int[contentSplit.length];

            for(int i = 0; i < contentSplit.length; i++) {
                input[i] = Integer.parseInt(contentSplit[i]);
            }

            System.out.println(input.length);
            measureSortAlgorithm(algorithm, input);
        }


    }
}
